// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: msgB.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "msgB.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* MessageB_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  MessageB_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_msgB_2eproto() {
  protobuf_AddDesc_msgB_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "msgB.proto");
  GOOGLE_CHECK(file != NULL);
  MessageB_descriptor_ = file->message_type(0);
  static const int MessageB_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageB, f1_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageB, f2_),
  };
  MessageB_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      MessageB_descriptor_,
      MessageB::default_instance_,
      MessageB_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageB, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(MessageB, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(MessageB));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_msgB_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    MessageB_descriptor_, &MessageB::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_msgB_2eproto() {
  delete MessageB::default_instance_;
  delete MessageB_reflection_;
}

void protobuf_AddDesc_msgB_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\nmsgB.proto\"\"\n\010MessageB\022\n\n\002f1\030\001 \002(\005\022\n\n\002"
    "f2\030\002 \002(\t", 48);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "msgB.proto", &protobuf_RegisterTypes);
  MessageB::default_instance_ = new MessageB();
  MessageB::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_msgB_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_msgB_2eproto {
  StaticDescriptorInitializer_msgB_2eproto() {
    protobuf_AddDesc_msgB_2eproto();
  }
} static_descriptor_initializer_msgB_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int MessageB::kF1FieldNumber;
const int MessageB::kF2FieldNumber;
#endif  // !_MSC_VER

MessageB::MessageB()
  : ::google::protobuf::Message() {
  SharedCtor();
}

void MessageB::InitAsDefaultInstance() {
}

MessageB::MessageB(const MessageB& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
}

void MessageB::SharedCtor() {
  _cached_size_ = 0;
  f1_ = 0;
  f2_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

MessageB::~MessageB() {
  SharedDtor();
}

void MessageB::SharedDtor() {
  if (f2_ != &::google::protobuf::internal::kEmptyString) {
    delete f2_;
  }
  if (this != default_instance_) {
  }
}

void MessageB::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* MessageB::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return MessageB_descriptor_;
}

const MessageB& MessageB::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_msgB_2eproto();
  return *default_instance_;
}

MessageB* MessageB::default_instance_ = NULL;

MessageB* MessageB::New() const {
  return new MessageB;
}

void MessageB::Clear() {
  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    f1_ = 0;
    if (has_f2()) {
      if (f2_ != &::google::protobuf::internal::kEmptyString) {
        f2_->clear();
      }
    }
  }
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool MessageB::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) return false
  ::google::protobuf::uint32 tag;
  while ((tag = input->ReadTag()) != 0) {
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // required int32 f1 = 1;
      case 1: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_VARINT) {
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &f1_)));
          set_has_f1();
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectTag(18)) goto parse_f2;
        break;
      }

      // required string f2 = 2;
      case 2: {
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED) {
         parse_f2:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_f2()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8String(
            this->f2().data(), this->f2().length(),
            ::google::protobuf::internal::WireFormat::PARSE);
        } else {
          goto handle_uninterpreted;
        }
        if (input->ExpectAtEnd()) return true;
        break;
      }

      default: {
      handle_uninterpreted:
        if (::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          return true;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
  return true;
#undef DO_
}

void MessageB::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // required int32 f1 = 1;
  if (has_f1()) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->f1(), output);
  }

  // required string f2 = 2;
  if (has_f2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->f2().data(), this->f2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->f2(), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
}

::google::protobuf::uint8* MessageB::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // required int32 f1 = 1;
  if (has_f1()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->f1(), target);
  }

  // required string f2 = 2;
  if (has_f2()) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8String(
      this->f2().data(), this->f2().length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE);
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->f2(), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  return target;
}

int MessageB::ByteSize() const {
  int total_size = 0;

  if (_has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    // required int32 f1 = 1;
    if (has_f1()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->f1());
    }

    // required string f2 = 2;
    if (has_f2()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->f2());
    }

  }
  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void MessageB::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const MessageB* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const MessageB*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void MessageB::MergeFrom(const MessageB& from) {
  GOOGLE_CHECK_NE(&from, this);
  if (from._has_bits_[0 / 32] & (0xffu << (0 % 32))) {
    if (from.has_f1()) {
      set_f1(from.f1());
    }
    if (from.has_f2()) {
      set_f2(from.f2());
    }
  }
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void MessageB::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void MessageB::CopyFrom(const MessageB& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool MessageB::IsInitialized() const {
  if ((_has_bits_[0] & 0x00000003) != 0x00000003) return false;

  return true;
}

void MessageB::Swap(MessageB* other) {
  if (other != this) {
    std::swap(f1_, other->f1_);
    std::swap(f2_, other->f2_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata MessageB::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = MessageB_descriptor_;
  metadata.reflection = MessageB_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
